import { canAutoFill, type ConfidenceCandidate } from '../core/confidence-policy';
import { AUTOMATIC_CANDIDATE_THRESHOLD, scoreCaptchaCandidate } from '../core/candidate-scorer';
import { matchCaptchaField } from '../core/field-matcher';
import { resultInterpreter } from '../core/result-interpreter';
import type { OcrResult, RecognitionMode, WorkflowResult } from '../core/types';
import { fillEmptyField } from './field-fill';
import type { ImageAcquisitionResult } from './image-source';
import { snapshotForImage, type ImageDetailSnapshot } from './dom-snapshot';

export type WorkflowTrigger = 'automatic' | 'explicit' | 'context';
export interface CaptchaWorkflow { run(image: HTMLImageElement, trigger: WorkflowTrigger): Promise<WorkflowResult>; cancel?(image: HTMLImageElement): void }
export interface CaptchaWorkflowOptions { snapshot?: (image: HTMLImageElement) => ImageDetailSnapshot; acquire: (image: HTMLImageElement) => Promise<ImageAcquisitionResult>; recognize: (dataUrl: string, revision: string, modes: readonly RecognitionMode[]) => Promise<readonly OcrResult[]> }
const MODES: readonly RecognitionMode[] = ['digits', 'letters', 'alphanumeric', 'arithmetic'];
const tokens = new WeakMap<HTMLImageElement, number>();
function errorResult(candidateId: string, error: unknown): WorkflowResult { const code = typeof error === 'object' && error !== null && 'code' in error ? (error as { code?: string }).code : undefined; return code === 'model_unavailable' ? { state: 'model_unavailable', candidateId } : { state: 'recognition_failed', candidateId }; }
function choose(results: readonly OcrResult[]): Exclude<ConfidenceCandidate, { kind: 'invalid' }> | undefined { const valid = resultInterpreter.interpret(results).map((result, index) => result.kind === 'invalid' ? result : { ...result, mode: results[index]!.mode }).filter((result): result is Exclude<ConfidenceCandidate, { kind: 'invalid' }> => result.kind !== 'invalid'); const byValue = new Map<string, Exclude<ConfidenceCandidate, { kind: 'invalid' }>>(); for (const result of valid) { const previous = byValue.get(result.fillValue); if (!previous || result.confidence > previous.confidence) byValue.set(result.fillValue, result); } const ranked = [...byValue.values()].sort((a, b) => b.confidence - a.confidence); const winner = ranked[0]; if (!winner || !canAutoFill(winner)) return undefined; return ranked[1] && winner.confidence - ranked[1].confidence < .1 ? undefined : winner; }
export function createCaptchaWorkflow(options: CaptchaWorkflowOptions): CaptchaWorkflow { const snapshot = options.snapshot ?? snapshotForImage; return { cancel(image) { tokens.set(image, (tokens.get(image) ?? 0) + 1); }, async run(image, trigger) { const first = snapshot(image); const candidateId = first.candidate.id; if (trigger === 'automatic' && scoreCaptchaCandidate(first.candidate.candidate).score < AUTOMATIC_CANDIDATE_THRESHOLD) return { state: 'no_candidate' }; const token = (tokens.get(image) ?? 0) + 1; tokens.set(image, token); let acquired: ImageAcquisitionResult; try { acquired = await options.acquire(image); } catch { return { state: 'image_unavailable', candidateId }; } if (acquired.state !== 'ready') return acquired.reason === 'permission' ? { state: 'permission_denied', candidateId } : { state: 'image_unavailable', candidateId }; let results: readonly OcrResult[]; try { results = await options.recognize(acquired.dataUrl, acquired.revision, MODES); } catch (error) { return errorResult(candidateId, error); } const current = snapshot(image); if (tokens.get(image) !== token || current.candidate.revision !== first.candidate.revision) return { state: 'stale', candidateId }; const selected = choose(results); if (!selected) return { state: 'needs_confirmation', candidateId, displayText: '', fieldIds: current.fields.map((item) => item.id) }; const match = matchCaptchaField(image, current.fields.map((item) => item.field)); if (match.state === 'none') return { state: 'no_field', candidateId, displayText: selected.displayText, fillValue: selected.fillValue }; if (match.state === 'ambiguous') return { state: 'needs_confirmation', candidateId, displayText: selected.displayText, fillValue: selected.fillValue, fieldIds: match.candidates.map((item) => item.field.id) }; const target = current.fields.find((item) => item.id === match.winner.id); if (!target) return { state: 'stale', candidateId }; const fill = fillEmptyField(target.element, selected.fillValue); return fill.state === 'filled' ? { state: 'filled', candidateId, fieldId: target.id, displayText: selected.displayText, fillValue: selected.fillValue } : fill.state === 'stale' ? { state: 'stale', candidateId } : { state: 'no_field', candidateId, displayText: selected.displayText, fillValue: selected.fillValue }; } }; }
